### ISSUE TITLE
Missing attribute "backend"

### ISSUE THREAD

**Issue by p0rtL6** [pyreadline3/pyreadline3#37]
Using this library introduces an error into anything that tries to access the "backend" attribute of Readline. This is included [here](https://docs.python.org/3/library/readline.html#readline.backend) in the standard library version of Readline, but not in this library.

Some other standard libraries like [cmd](https://docs.python.org/3/library/cmd.html) rely on this functionality: [source code](https://github.com/python/cpython/blob/3.13/Lib/cmd.py#L111).

This problem is easily fixed by just setting the backend attribute to "readline" on the library. Is this something that was just missed or intentionally not set because there are other compatibility issues with the libraries that rely on it?

**Comment by jmw182** [comment]
I noticed this issue too, specifically after updating to python 3.13 and trying to use `pdb` via the `breakpoint()` function. This library is generally not working with python 3.13, see also #36.

**Comment by harkabeeparolus** [comment]
To reproduce, on Windows 11:

```text
❯ uv self version
uv 0.7.10 (1e5120e15 2025-06-03)

❯ uv run --python 3.13 python -m platform
Windows-11-10.0.26100-SP0

❯ uv run --python 3.13 --with pyreadline3==3.5.4 python -c 'import cmd; cmd.Cmd().cmdloop()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import cmd; cmd.Cmd().cmdloop()
                ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\traal\AppData\Roaming\uv\python\cpython-3.13.3-windows-x86_64-none\Lib\cmd.py", line 111, in cmdloop
    if readline.backend == "editline":
       ^^^^^^^^^^^^^^^^
AttributeError: module 'readline' has no attribute 'backend'
```

**Comment by stonebig** [comment]
problem is, this library is used indrectly per onnxruntime:

<img width="1555" height="200" alt="Image" src="https://github.com/user-attachments/assets/1ba59e6e-7648-4eaf-8d7c-fc740516be1f" />

**Comment by zelosleone** [comment]
should be solved with this if the maintainers ever merge it https://github.com/pyreadline3/pyreadline3/pull/44

**Comment by Windows81** [comment]
> should be solved with this if the maintainers ever merge it [#44](https://github.com/pyreadline3/pyreadline3/pull/44)

**This works on my Windows machine.**

```
pip install --force-reinstall git+https://github.com/zelosleone/pyreadline3.git@add-backend-readline
```

---

Before:
```
PS C:\Users\USER> py
Python 3.13.11 (tags/v3.13.11:6278944, Dec  5 2025, 16:26:58) [MSC v.1944 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Failed calling sys.__interactivehook__
Traceback (most recent call last):
  File "<frozen site>", line 536, in register_readline
AttributeError: module 'readline' has no attribute 'backend'
>>>
```

After:
```
PS C:\Users\USER> py
Python 3.13.11 (tags/v3.13.11:6278944, Dec  5 2025, 16:26:58) [MSC v.1944 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by thomas-haslwanter** [comment]
I can confirm that problem on Python 3.13 and Python 3.14

**Comment by brgirgis** [comment]
@p0rtL6, please check recent version 3.5.5 and close this issue if fixed

**Comment by harkabeeparolus** [comment]
Confirmed fixed for me! 😊

```text
C:\Users\traal> uv run --with pyreadline3==3.5.4 python -c 'import cmd; cmd.Cmd().cmdloop()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import cmd; cmd.Cmd().cmdloop()
                ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\traal\AppData\Roaming\uv\python\cpython-3.14-windows-x86_64-none\Lib\cmd.py", line 114, in cmdloop
    if readline.backend == "editline":
       ^^^^^^^^^^^^^^^^
AttributeError: module 'readline' has no attribute 'backend'

C:\Users\traal> uv run --with pyreadline3==3.5.6 python -c 'import cmd; cmd.Cmd().cmdloop()'
(Cmd)
```

**Comment by p0rtL6** [comment]
Closing as fixed!
